services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
